# docker-compose.test.yml
services:
    ecom:
        image: bitnami/mysql:8.0
        container_name: ecom_test_db
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "5433:5432"  # Different port from dev database
        environment:
            POSTGRES_DB: ecom_test_db
            POSTGRES_USER: test_user
            POSTGRES_PASSWORD: test_password
            MYSQL_ROOT_PASSWORD: root_password
        tmpfs:
            - /var/lib/mysql
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "test_user", "-ptest_password" ]
            interval: 10s
            timeout: 5s
            retries: 5
