export const CART_SERVICE_TOKEN = Symbol('CART_SERVICE_TOKEN');
export const CART_REPOSITORY_TOKEN = Symbol('CART_REPOSITORY_TOKEN');
export const CART_PRODUCT_REPOSITORY_TOKEN = Symbol('CART_PRODUCT_REPOSITORY_TOKEN');

export const CART_UPDATE_QUANTITY_UOW = Symbol('CART_UPDATE_QUANTITY_UOW');
export const CART_UPDATE_QUANTITY_USE_CASE = Symbol('CART_UPDATE_QUANTITY_USE_CASE');
